import type { Metadata } from 'next';
import '@ant-design/v5-patch-for-react-19';
import './globals.css';
import { AuthInitializer } from '../app/components/AuthInitializer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='preload'
          href='https://fonts.googleapis.com/css2?family=Mona+Sans:ital,wght@0,200..900;1,200..900&display=swap'
          as='style'
        />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Mona+Sans:ital,wght@0,200..900;1,200..900&display=swap'
        />
      </head>
      <body className='antialiased bg-[#F8F9FA] font-mona-sans'>
        <AuthInitializer>{children}</AuthInitializer>
      </body>
    </html>
  );
}
